import { Badge, Empty, ErrorBox, Loading, PageHeader } from '../components';
import { useApi } from '../hooks';

export function TasksPage() { const s = useApi<any>('/tasks'); if (s.loading) return <Loading/>; return <><PageHeader title="قائمة الانتظار" description="المهام الدائمة والمحاولات وحالة التنفيذ."/>{s.error && <ErrorBox message={s.error}/>}<div className="table-wrap"><table><thead><tr><th>المهمة</th><th>الحالة</th><th>المحاولات</th><th>موعد التشغيل</th><th>آخر خطأ</th></tr></thead><tbody>{s.data?.items.map((x: any) => <tr key={x.id}><td><strong>{x.type}</strong><div className="text-xs text-slate-400">{x.idempotencyKey}</div></td><td><Badge status={x.status}/></td><td>{x.attempts}/{x.maxAttempts}</td><td>{new Date(x.runAt).toLocaleString('ar-EG')}</td><td className="max-w-xs truncate text-rose-600">{x.lastError ?? '—'}</td></tr>)}</tbody></table></div></>; }
export function NotificationsPage() { const s = useApi<any>('/notifications'); if (s.loading) return <Loading/>; return <><PageHeader title="التنبيهات" description="الأحداث التي تحتاج انتباهك."/><div className="space-y-3">{s.data?.items.map((x: any) => <article className={`card ${x.readAt ? 'opacity-60' : 'border-r-4 border-r-amber-500'}`} key={x.id}><div className="flex justify-between"><strong>{x.title}</strong><span className="text-xs text-slate-400">{new Date(x.createdAt).toLocaleString('ar-EG')}</span></div><p className="mt-2 text-sm text-slate-600">{x.message}</p></article>)}</div>{!s.data?.items.length && <Empty/>}</>; }
export function ActivityPage() { const s = useApi<any>('/activity'); if (s.loading) return <Loading/>; return <><PageHeader title="سجل النشاط" description="أثر تدقيقي لكل قرار يدوي وآلي."/><div className="space-y-3">{s.data?.items.map((x: any) => <article className="card flex gap-4" key={x.id}><div className="mt-1 h-3 w-3 shrink-0 rounded-full bg-brand-500"/><div><strong>{x.action}</strong><p className="text-sm text-slate-500">{x.entityType} {x.entityId ? `• ${x.entityId}` : ''} • {x.source === 'USER' ? `المستخدم ${x.user?.username ?? ''}` : 'الأتمتة'}</p><time className="text-xs text-slate-400">{new Date(x.createdAt).toLocaleString('ar-EG')}</time></div></article>)}</div></>; }

export function PostsPage() { const s = useApi<any>('/posts'); if (s.loading) return <Loading/>; return <><PageHeader title="المنشورات" description="كل منشور يحتفظ بنسخة المحتوى التي أُرسلت إلى الجروب."/><div className="table-wrap"><table><thead><tr><th>الوظيفة والتصنيف</th><th>الجروب</th><th>المحتوى</th><th>الحالة</th><th>رقم الإعادة</th><th>وقت النشر</th></tr></thead><tbody>{s.data?.items.map((x: any) => <tr key={x.id}><td><strong>{x.job.title}</strong><div className="text-xs text-slate-500">{x.job.category}</div></td><td>{x.group.name}</td><td><details className="max-w-md"><summary className="cursor-pointer font-semibold">معاينة البوست</summary><p className="mt-2 whitespace-pre-wrap text-sm">{x.content}</p></details></td><td><Badge status={x.status}/></td><td>{x.repostNumber}</td><td>{x.postedAt ? new Date(x.postedAt).toLocaleString('ar-EG') : '—'}</td></tr>)}</tbody></table></div></>; }

export function ErrorsPage() { const s = useApi<any>('/errors'); if (s.loading) return <Loading/>; return <><PageHeader title="الأخطاء والتدخل اليدوي" description="الأخطاء المفتوحة مع التفاصيل التقنية ولقطات الشاشة."/><div className="space-y-3">{s.data?.items.map((x: any) => <article className="card" key={x.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-rose-700">{x.message}</strong><p className="mt-1 text-xs text-slate-500">{x.type} • {new Date(x.createdAt).toLocaleString('ar-EG')} • محاولة {x.retryCount}</p></div><div className="flex gap-2">{x.screenshots.map((shot: any) => <a className="btn-secondary" target="_blank" href={`/api/screenshots/${shot.id}`} key={shot.id}>عرض اللقطة</a>)}</div></div><details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">التفاصيل التقنية</summary><pre dir="ltr" className="mt-2 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-200">{x.technical ?? x.stack}</pre></details></article>)}</div>{!s.data?.items.length && <Empty text="لا توجد أخطاء مفتوحة."/>}</>; }
