import type { ReactNode } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, LoaderCircle, XCircle } from 'lucide-react';

export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) {
  return <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-extrabold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{actions}</header>;
}

const statusStyle: Record<string, string> = {
  JOINED: 'bg-emerald-50 text-emerald-700', APPROVED: 'bg-emerald-50 text-emerald-700', POSTED: 'bg-emerald-50 text-emerald-700', ACCEPTED_BY_RULES: 'bg-emerald-50 text-emerald-700', MANUALLY_ACCEPTED: 'bg-emerald-50 text-emerald-700', COMPLETED: 'bg-emerald-50 text-emerald-700',
  WAITING_ADMIN: 'bg-amber-50 text-amber-700', PENDING_ADMIN_APPROVAL: 'bg-amber-50 text-amber-700', NEEDS_QUESTIONS: 'bg-amber-50 text-amber-700', QUEUED: 'bg-blue-50 text-blue-700', RUNNING: 'bg-blue-50 text-blue-700', ACTIVE: 'bg-blue-50 text-blue-700',
  REJECTED: 'bg-rose-50 text-rose-700', JOIN_REJECTED: 'bg-rose-50 text-rose-700', REJECTED_BY_RULES: 'bg-rose-50 text-rose-700', MANUALLY_REJECTED: 'bg-rose-50 text-rose-700', FAILED: 'bg-rose-50 text-rose-700',
  MANUAL_ACTION_REQUIRED: 'bg-orange-50 text-orange-700', PAUSED: 'bg-slate-100 text-slate-700', STOPPED: 'bg-slate-100 text-slate-700', DRAFT: 'bg-slate-100 text-slate-700',
};
const labels: Record<string, string> = { JOINED: 'منضم', APPROVED: 'مقبول', POSTED: 'منشور', ACCEPTED_BY_RULES: 'مقبول آليًا', MANUALLY_ACCEPTED: 'مقبول يدويًا', COMPLETED: 'مكتمل', WAITING_ADMIN: 'بانتظار الأدمن', PENDING_ADMIN_APPROVAL: 'بانتظار الموافقة', NEEDS_QUESTIONS: 'يحتاج إجابات', QUEUED: 'في الانتظار', RUNNING: 'يعمل', ACTIVE: 'نشط', REJECTED: 'مرفوض', JOIN_REJECTED: 'رفض الانضمام', REJECTED_BY_RULES: 'مرفوض آليًا', MANUALLY_REJECTED: 'مرفوض يدويًا', FAILED: 'فشل', MANUAL_ACTION_REQUIRED: 'تدخل يدوي', PAUSED: 'متوقف مؤقتًا', STOPPED: 'متوقف', DRAFT: 'مسودة', NOT_JOINED: 'غير منضم', NEW: 'جديد', ANALYZING: 'قيد التحليل', WOULD_POST: 'سيتم النشر (تجريبي)' };
export function Badge({ status }: { status: string }) { return <span className={`inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-bold ${statusStyle[status] ?? 'bg-slate-100 text-slate-700'}`}>{labels[status] ?? status}</span>; }
export function Loading() { return <div className="flex min-h-56 items-center justify-center text-slate-500"><LoaderCircle className="ml-2 animate-spin" /> جارٍ التحميل...</div>; }
export function Empty({ text = 'لا توجد بيانات بعد.' }: { text?: string }) { return <div className="card py-14 text-center text-slate-500">{text}</div>; }
export function ErrorBox({ message }: { message: string }) { return <div className="mb-4 flex items-center gap-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><XCircle size={18} />{message}</div>; }
export function StatCard({ title, value, tone = 'green' }: { title: string; value: number | string; tone?: 'green' | 'amber' | 'red' | 'blue' }) { const colors = { green: 'bg-brand-50 text-brand-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-rose-50 text-rose-700', blue: 'bg-blue-50 text-blue-700' }; const Icon = tone === 'red' ? AlertTriangle : tone === 'amber' ? Clock3 : CheckCircle2; return <div className="card"><div className={`mb-4 inline-flex rounded-xl p-2.5 ${colors[tone]}`}><Icon size={20}/></div><div className="text-3xl font-extrabold">{value}</div><div className="mt-1 text-sm text-slate-500">{title}</div></div>; }
export function Pagination({ page, total, pageSize, onPage }: { page: number; total: number; pageSize: number; onPage: (p: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="mt-4 flex items-center justify-between text-sm"><span className="text-slate-500">{total.toLocaleString('ar-EG')} نتيجة</span><div className="flex gap-2"><button className="btn-secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>السابق</button><span className="px-3 py-2">{page} / {pages}</span><button className="btn-secondary" disabled={page >= pages} onClick={() => onPage(page + 1)}>التالي</button></div></div>; }
